### ISSUE TITLE
input_log doesn't append newlines

### ISSUE THREAD

**Issue by ZenT3600** [umanochiocciola/kane#3]
When writing the input_log, the program doesn't append a newline at the end of every command, so it all looks something like "lsdirpwdpwdexitlogout"

![immagine](https://user-images.githubusercontent.com/40890172/101875899-bea66180-3b8b-11eb-9b15-b0c211891c56.png)

**Comment by umanochiocciola** [comment]
Yeah that's awful, I'll fix it.
