### ISSUE TITLE
user's password is shown in plain text

### ISSUE THREAD

**Issue by ZenT3600** [umanochiocciola/kane#4]
When creating a new user, its realitive UserData.dat file contains the password in plain text. it looks something like

![immagine](https://user-images.githubusercontent.com/40890172/101876102-2a88ca00-3b8c-11eb-8b7e-11db0c7c594c.png)

my password in this case is "pippo"
There's also something else. Probably the creation date of the user, but that's just an assumption

**Comment by umanochiocciola** [comment]
Damn I forgot to include the encription algorithm. The date is the last day of update checking. Fixing it straight away. Thanks!
